SELECT p.NUMBER_, erl.ID, erl.PRESCRIPTION_ID, erl.TIME_STAMP::text AS TIME, erl.EVENT_CODE, erl.IDENT, erl.POS_IDENT, erl.EVENT_RESULT, erl.EVENT_DETAILS, erl.REQUEST_GUID, erl.RESPONSE_GUID, erl.SALE_DATE::date, erl.PRESENTATION_DATE::date, erl.SERVICE_PERIOD
FROM llo.PRESCRIPTION p
JOIN llo.E_RECIPE_LOG erl ON erl.PRESCRIPTION_ID  = p.ID
WHERE p.NUMBER_ = ANY(string_to_array(%(numbers)s, ','))
limit  10000
