SELECT p.ID, p.DIAGNOSIS, p.NUMBER_, p.FORM_NUMBER, p.STATE, p.DISEASE_CODE, p.DOCTOR_ID,
       p.LPU_ID, p.PATIENT_ID, p.SPECIALITY_ID, p.TYPE_, p.MEDICAL_RECORD, p.NUMBER_DAYS,
       p.JOB_SPEC, p.DOCTOR_CODE, p.MO_DZM_CODE, p.MO_OGRN, p.PATIENT_HASH, p.CONTROL_TYPE,
       p.DOCTOR_SECOND_NAME, p.DOCTOR_FIRST_NAME, p.DOCTOR_PARENTAL_NAME, p.PROTOCOL_ID,
       p.PRESCRIPTION_RECORD_ID, p.CTIME::text, p.EXPIRATION_DATE::text, p.PHARMACY_ID,
       p.PRESCRIPTION_EHR_ID, p.CONTROLLED_NUMBER, p.E_RECIPE, p.BIRTH_CERTIFICATE, p.PERIODICITY
FROM llo.PRESCRIPTION p
WHERE p.NUMBER_ = ANY(string_to_array(%(numbers)s, ','))
limit 10000


