SELECT p.NUMBER_, ps.ID, ps.STATE, ps.PHARMACY_ID, ps.PRESCRIPTION_ID, ps.SALE_PRICE_COPECK,
       ps.DRUGS_NAME, ps.QUANTITY, ps.UNIT_NAME, ps.COMMENT_, ps.TRADE_NAME_ID, ps.TRADE_FNAME_ID,
       ps.EVENT_DATE::text, ps.SALE_DATE::text, ps.PHARMACSTIC_SNILS, ps.PHARMASTIC_POSITION,
       ps.PHARMACIST_FULL_NAME, ps.SALE_MODE
FROM llo.PRESCRIPTION p
    JOIN llo.PRESCRIPTION_SERVICING ps ON ps.PRESCRIPTION_ID = p.ID
WHERE p.NUMBER_ = ANY(string_to_array(%(numbers)s, ','))
limit  10000
