SELECT p.NUMBER_, pe.ID, pe.PRESCRIPTION_ID, pe.EVENT_DESCRIPTION, pe.ORG_UID, pe.OPERATOR_JOB,
       pe.EVENT_TYPE, pe.EVENT_RESULT, pe.OPERATOR_UID, pe.STATE_BEFORE, pe.STATE_AFTER,
       pe.TIME_STAMP::text
FROM llo.PRESCRIPTION_EVENTS pe
    JOIN llo.PRESCRIPTION p ON p.ID = pe.PRESCRIPTION_ID
    WHERE p.NUMBER_ = ANY(string_to_array(%(numbers)s, ','))
    ORDER BY pe.TIME_STAMP desc
limit  10000
