[app]
environment = "development"
debug = false

[database]
dialect = "postgres"
host = "172.16.132.151"
port = 5432
user = "nbb"
password = "spargo_26"
database = "nbb"

[delivery.nextcloud]
url = "https://cloud.yourcompany.com"
username = "report_bot"
password = "app-specific-password-here"

[delivery.mail]
smtp_server = "smtp.yourcompany.com"
smtp_port = 587
use_tls = true
sender = "reporter@yourcompany.com"
password = "email_password"

[delivery.yandex_messenger]
bot_token = "AgAAAAA..." # Токен вашего бота для отправки ОТЧЕТОВ пользователям

[monitoring]
yandex_chat_id = "admin_chat_id_here" # Сюда будут сыпаться АЛЕРТЫ в случае падения системы
yandex_bot_token = "bot_token_here"


