SELECT d.ID, d.EXTERNAL_ID, d.AGGREGATOR_ID, d.PHARMACY_ID, d.PATIENT_EMIAS_ID,
 d.CREATED_DATE, d.FINAL_STATUS, d.EXTERNAL_STATUS, d.EXTERNAL_STATUS_COMMENT, 
 d.CLOSING_DATE, d.DELIVERING, d.PHARMACIST_SNILS, d.PHARMACIST_POSITION, d.LINK, d.PHARMACIST_NAME 
FROM llo.DRUG_ORDER d 
WHERE d.EXTERNAL_ID = ANY(string_to_array(%(ext_numbers)s, ','))
limit 10000    
